### ISSUE TITLE
Failed when trying to install Hedgedoc.

### ISSUE THREAD

**Issue by SimonLefort** [YunoHost-Apps/hedgedoc_ynh#14] opened 2021-01-29 18:06 UTC
Hello,

**Describe the bug**
I was trying to install Hedgedoc on a sub-domain. It didn't work and the application wasn't installed.

**Versions**
- Hardware: Kimsufi KS-3 Server
- YunoHost version: 4.1.6 (everything up-to-date)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.7.2

**To Reproduce**
I tried from the webadmin but it's the same from the CLI : 

```sh
    $ sudo yunohost app install hedgedoc
    Choose the domain where this app should be installed [mydomain.be | cloud.mydomain.be | pad.mydomain.be] (default: mydomain.be): pad.mydomain.be
    Choose the path where this app should be installed (default: /hedgedoc): /
    Should this app be exposed to anonymous visitors? [yes | no] (default: yes): yes
    Info: Installing hedgedoc...
    Info: [....................] > Validating installation parameters...
    Info: [....................] > Storing installation settings...
    Info: [+...................] > Finding an available port...
    Info: [#++++++.............] > Installing dependencies...
    Info: Installation of N - Node.js version management
    Info: '/etc/apt/trusted.gpg.d/hedgedoc.asc' wasn't deleted because it doesn't exist.
    Info: [#######+............] > Creating a PostgreSQL database...
    Info: [########+...........] > Setting up source files...
    Info: [#########...........] > Configuring NGINX web server...
    Info: [#########+..........] > Configuring system user...
    Info: [##########++++++....] > Building HedgeDoc... (this will take some time and resources!)
    Warning: error /var/www/hedgedoc/node_modules/sqlite3: Command failed.
    Warning: Exit code: 1
    (...)
```

**Expected behavior**
I expected Hedgedoc installation.

**Logs**
The logs are there : https://paste.yunohost.org/raw/egofapesoy

**Comment by kingannoy** [comment] 2021-03-19 23:25
I figured out what is probably the cause for this issue!

I have tried this installation multiple times over multiple months and it consistently failed for me too, in seemingly exactly the same way:
https://paste.yunohost.org/raw/ofayamodoz

I'm on a Debian VPS (1 GB Ram, 1 CPU)
I'm on Yunohost version: 4.1.7.4
Installing HedgeDoc version: 1.7.2

I found a clue in the "Diagnosis" page of Yunohost, there I saw the following:

![image](https://user-images.githubusercontent.com/36500946/111851188-9d83a880-8912-11eb-93dc-fc2f55d7f605.png)

So I shut down the machine, assigned more ram, booted and tried again. That solved the issue!

**Comment by lapineige** [comment] 2021-03-21 08:34
Yeah it seems that the memory consumption is still too high for 1GB RAM systems… :(

It sounds like 3GB are needed, maybe 2GB could be enough, but I'm unsure…
How many free RAM did you have during your test ?

(closing because "solved")

**Closed by lapineige** 2021-03-21 08:34 UTC

**Comment by kingannoy** [comment] 2021-03-22 10:10
I ran the install with 3 GB. Afterwards I scaled back to 2 GB. This seems to work fine.

**Comment by SimonLefort** [comment] 2021-03-22 10:12
My server has 4GB of RAM and it doesn't work. Everything is up-to-date.

https://paste.yunohost.org/raw/ahuwalibov

I don't understand these errors. :-/
